default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db_heroku_development
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: MojeHeslo

test:
  <<: *default
  database: db_heroku_test

production:
  adapter: postgresql
  encoding: unicode
  database: db_production
  host: localhost
  pool: 5
  username: postgres
  password: <%= ENV['DB_HEROKU_DATABASE_PASSWORD'] %>
